site_name: 'BitDocs'
repo_url: https://github.com/bitdocs/bitdocs-code
site_url: https://bitdocs.ml
site_description: A documentation for the Little Bits electronic components.
site_author: Sean Maizel and Calum Dingwall
copyright: Made by Sean Maizel and Calum Dingwall
nav:
    - Home: index.md
    - About: about.md
    - Modules (Bits):
        Power: power.md
        Outputs:
            Page 1: output.md
            Page 2: output-2.md
theme:
    name: cinder
    custom_dir: 'cinder-theme-ext/'
extra_css: 
    - css/colors.css
